volumes:
  node_modules:
services:
  my-nuxt-app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "24678:24678"
    volumes:
      - ./app:/app
      - node_modules:/src/node_modules
#docker compose -f docker-compose.yaml -f docker-compose.dev.yaml up --build -d
